### ISSUE TITLE
HTML for the github area

### ISSUE THREAD

**Issue by KoneeVibes** [kingfavour28/Portfolio#2]
Great HTML so far. Just how you've structure the html for the about section (class naming etc.), you will do same for the github area.

**Comment by KoneeVibes** [comment]
> Great HTML so far. Just how you've structure the html for the hero section (class naming etc.), you will do same for the github area.

Please note that the div that reads - "Contact Us" is not a part of the github area. We can do that together on a 1hr call, it's a bit complex and involves CSS.

**Comment by kingfavour28** [comment]
The Github image and Html Structure is now complete.
