### ISSUE TITLE
Set up CSS stylesheet

### ISSUE THREAD

**Issue by KoneeVibes** [kingfavour28/Portfolio#4]
1. Create a new file in the root folder. name it `style.css `.  This is the file that will contain all our stylings.
2. Inside the `index.html `, in the head, paste this code block `<link rel="stylesheet" href="style.css"> `

**Comment by KoneeVibes** [comment]
> 1. Create a new file in the root folder. name it `style.css `.  This is the file that will contain all our stylings.
> 2. Inside the `index.html `, in the head, paste this code block `<link rel="stylesheet" href="style.css"> `

Ref article - https://www.w3schools.com/html/html_css.asp

**Comment by kingfavour28** [comment]
Done
