### ISSUE TITLE
Style the navbar

### ISSUE THREAD

**Issue by KoneeVibes** [kingfavour28/Portfolio#5]
### 1. Inside your `style.css`, you will select the navbar class and style it's background-color, padding, display, gap like below:
```
.navbar {
    background-color: black;
    padding: 1rem;
    display: flex;
    gap: 1rem;
}
```
### 2. Inside your `style.css`, you will select the a elements inside the navbar class and style it's text-decoration and color like below:
```
.navbar a {
    text-decoration: none;
    color: white;
}
```
### 3. Inside your `style.css`, you will select the body element and style it's margin and padding like below:
```
body {
    margin: 0;
    padding: 0;
}
```

The navbar should look like this when you are done:

![image](https://github.com/user-attachments/assets/b6a0be29-90b1-4734-83a0-44d662bf361c)

**Comment by kingfavour28** [comment]
Done
