### ISSUE TITLE
Style the hero

### ISSUE THREAD

**Issue by KoneeVibes** [kingfavour28/Portfolio#6]
### 1. Inside the `style.css`, you will style the hero section with padding and background-color properties like below:
```
.hero {
    padding: 1rem;
    background-color: transparent;
}
```
### 2. Inside the `style.css`, you will style the h1 and p elements in the hero div respectively with a text-align property like below:
```
.hero h1 {
    text-align: center;
}

.hero p {
    text-align: center;
}
```

We can add the background video over a call but now, the hero should now look like this:
![image](https://github.com/user-attachments/assets/5ef6c396-74c5-4a13-95d5-0cfe778aa281)

**Comment by kingfavour28** [comment]
Done
